name: Tests

on:
  pull_request:
    branches:
      - main
      - develop
      - rc
  push:
    branches:
      - main # This will trigger the workflow on all pushes to the main branch

jobs:
  linting: # This job performs linting operations on Node.js version 20.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      #- run: chmod +x .husky/pre-commit # Husky için izinleri ayarla
      #- run: npm install -g husky
      #- run: HUSKY=0 npm install
      - run: npm run lint

  build: # This job builds the project with different Node.js versions.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x] # Add more versions as needed
    needs: linting
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
